######### Apache License ########################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


#################################################################################

AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack that manages two child stacks
Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment to deploy into
    AllowedValues: [dev, uat, prod]
  Audience:
    Type: String
    Description: 'Audience for HTTP API Authorizer'
  Issuer:
    Type: String
    Description: 'Issuer for HTTP API Authorizer'
  IdcInstanceArn:
    Type: String
    Description: "ARN of the Identity Center (IDC) Instance"    
  PluginDisplayName:
    Type: String
    Description: 'The display name for the plugin'
    MinLength: 1
    MaxLength: 100
    AllowedPattern: '^[a-zA-Z0-9][a-zA-Z0-9_-]*$'
    Default: 'CreateCase'
  ClientId:
    Type: String
    Description: 'OAuth2 Client ID'
  ClientSecret:
    Type: String
    Description: 'OAuth2 Client Secret'
  AuthorizationUrl:
    Type: String
    Description: 'OAuth2 Authorization URL'
  TokenUrl:
    Type: String
    Description: 'OAuth2 Token URL'
  SourceZipUrl:
    Type: String
    Default: "https://aws-blogs-artifacts-public.s3.us-east-1.amazonaws.com/ML-17430/webconnect/Archive.zip"
  ContainerPort:
    Type: Number 
    Default: 80
    Description: What port number the application inside the docker container is binding to
  RepositoryName:
    Type: String
    Default: "repo-demo"
    Description: "Base name for the ECR repository (lowercase letters and numbers only)"
    AllowedPattern: "^[a-z-0-9]*$"
    ConstraintDescription: "Repository name must contain only lowercase letters, numbers, and hyphens."

Resources:
  ChildStack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://aws-blogs-artifacts-public.s3.us-east-1.amazonaws.com/ML-17430/cloudformation/childstack1.yml'
      Parameters:
        Environment: !Ref Environment
        Audience: !Ref Audience
        Issuer: !Ref Issuer
        IdcInstanceArn: !Ref IdcInstanceArn
        PluginDisplayName: !Ref PluginDisplayName
        ClientId: !Ref ClientId
        ClientSecret: !Ref ClientSecret
        AuthorizationUrl: !Ref AuthorizationUrl
        TokenUrl: !Ref TokenUrl


  ChildStack2:
    Type: AWS::CloudFormation::Stack
    DependsOn: ChildStack1
    Properties:
      TemplateURL: 'https://aws-blogs-artifacts-public.s3.us-east-1.amazonaws.com/ML-17430/cloudformation/childstack2.yml'
      Parameters:
        AmazonQUrl: !GetAtt ChildStack1.Outputs.QBizWebexperienceURL
        SourceZipUrl: !Ref SourceZipUrl
        ContainerPort: !Ref ContainerPort
        RepositoryName: !Ref RepositoryName
Outputs:
  QBizWebexperienceURL:
    Description: "URL of the Amazon Q Web Experience"
    Value: !GetAtt ChildStack1.Outputs.QBizWebexperienceURL
  ALBDNSName:
    Description: "DNS Name of the ALB"
    Value: !GetAtt ChildStack2.Outputs.ALBDNSName